### PR TITLE
Using URL friendly names to images folders with backward compatibility.

### PR DESCRIPTION
**Pull request by AAbouZaid**
I removed brackets from images folder name to make them URL friendly and added part for backward compatibility specific for two icons themes, which are "stars_flat(png)' and "stars(png)".

I didn't make it a global solution for brackets to avoid any confusion in the future (e.g. someone forked the repo and decided to make new directory has brackets).

Also, it will automaticly change "postratings_image" once, so no need to any further actions form users.
Thanks.

### CODE REVIEW

**Comment by lesterchan** [comment]
The PR seems a bit hardcoded and the replacement can be done more elegantly. The whole block out code outside any function? That is wrong.

I think i will keep it as it is for now.

**Comment by AAbouZaid** [comment]
As I mentioned before, I hard-codded names to make sure there is no confusion in the future. So this is just a spacial fix for two themes  "stars_flat(png)" and "stars(png)".

If the code moved to postratings-activation.php would it activated when plugin updated?

I think standardization is enough reason, isn't it? :D

I'm just a sysadmin and don't have much experience with Wordpress, so feel free to make any suggestions :D

**Comment by lesterchan** [comment]
Thanks! I will take note of it. But as of now, I have no plans to touch it yet. Probably I will rewrite it to use CSS instead of images =)

**Comment by AAbouZaid** [comment]
It's a nice idea :D

**Pull request closed without merging**
