### PR TITLE
Replace die() with wp_die(), add i18n to the strings, phpDocs, header updates, translation strings and more...

### PR DESCRIPTION
**Pull request by ramiy**

### CODE REVIEW

**Comment by ramiy** [comment]
@lesterchan you need to consider rewriting the widget, or create several smaller widgets with different functionality.

**Comment by lesterchan** [comment]
Thanks Ramiy. Unlikely I got time to do rewrite anytime soon though. If I have the time, I will probably see how can I use CSS instead of images for the stars!

**Comment by lesterchan** [comment]
@ramiy is this tested? I merged this, now the admin doesn't show. It looks like the includes is broken. All the file being included is missing

**Comment by lesterchan** [comment]
I have no idea why the files are not being included on my end. I am on HHVM 3.11.0. When I prefixed it to "postratings-" it works https://github.com/lesterchan/wp-postratings/commit/e070880378b7bcca2190908fea510628454d2e92

**Comment by ramiy** [comment]
@lesterchan, just tested the plugin, works for me. I guess you already fixed it.

**Comment by lesterchan** [comment]
Yeap, it is damn weird! I tried admin.php it doesn't load the file but when I tried admin2.php it works! I think must be some weird HHVM JIT bug.

**Pull request merged**
