### PR TITLE
Downloadable reports

### PR DESCRIPTION
**Pull request by azibhassan**
Improve the functionality of downloading reports. Main purpose is to download the data to different formats of CSV

### CODE REVIEW

**Comment by nurikabe** [comment]
+1 

Hi @lesterchan.  If we are able to get this cleaned up to your liking, would you consider merging into the project?  Or would it be better for us to maintain a fork?

Thanks

**Comment by lesterchan** [comment]
I think it is better for you guys to maintain a fork =)

1. There is still conflict with the master branch which you did not rebase
2. There is no need for null options
3. You are not using any wpdb functions to query the DB.

**Comment by nurikabe** [comment]
Thanks Lester.  This is actually for a school project so the work is valuable experience.  We'll give it one more go.

**Comment by lesterchan** [comment]
I am very strict on what goes in because at the end of the day, I will be the one maintaining it and whatever code that goes in goes into a million sites.

**Comment by nurikabe** [comment]
No problem, totally understood.  Thank you for being so responsive!

**Comment by azibhassan** [comment]
I was wandering if you could help me with one suggestions of yours. You wanted me to move the code which is in wp-postrating.php to postrating-manager.php. I tried doing this many times but whenever I try to implement functions in postrating-manager.php downloading functions does not respond. Page just reloads and file does not download. If you can give me an idea regarding this that would be really helpful.

**Pull request closed without merging**
