### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by drzraf**
* avoid code/routine duplication
  especially for postratings_page_admin_most_stats() and get_ratings_images_vote()
* use ternary operator where it improve readability
* use here-doc where possible
* move wp_localize_script() where the_rating() actually display voting form
  and move part of its logic client-side => code simplification
* use document.getElementById() where it makes things simpler
  and alias jQuery to $j
* move some "static" file_exists() outside of loops and use a cleaner
  way to declare/implode() complex markup
* avoid double-escaping, let this task to wpdb() + use wpdb->insert()

this is the first part needed to adapt the code further deeper changes.
please review & merge ASAP ;)

### CODE REVIEW

**Comment by lesterchan** [comment]
This looks good, I branch out a branch called dev, can you send the PR to that branch, so that I can merge and test it rather than on master?

**Comment by drzraf** [comment]
I just added the last chunk I wanted: bind wp-postrating to wp-comment
=> rebased upon -dev
I hope you'll enjoy it

**Comment by lesterchan** [comment]
Actually what you mean by bind voting to comment submission.?

**Comment by lesterchan** [comment]
@drzraf actually what you mean by binding comment rating?

**Comment by drzraf** [comment]
It's to restrict votes to comment submission (people can't put stars without having to comment/explain their choice) => integration with the built-in WordPress comment system.
In this case (option enabled), the rating submission happen with the comment form and no more independently

**Comment by lesterchan** [comment]
So basically comment with ratings?

**Comment by drzraf** [comment]
yes (based on wp-postratings)

**Comment by drzraf** [comment]
any hint on how/when -dev is going to be merged onto master so that I can then rebase pr #95 and work on further improvements?

**Comment by lesterchan** [comment]
You can rebase the PR with dev and resubmit again to the dev branch.

It will not be so fast, it is the biggest code change submitted so I will probably going to let more people test it before releasing it. Maybe a few months? I got not much time to test as well.

You also need to note that if there are any bugs, I have to fix it in the future. So I rather not rush into it since it is not broken right now =)

**Comment by drzraf** [comment]
I can't rebase/force-push since the PR has been merged and thus closed.
I opened #99 for follow-up (there I moved the vote+comment related code into it's own file, this should make the merge safer)
I should admit that I won't have the energy to rework this PR in case of a conflict on master.

IMHO the only significant change is that the output of `wp_localize_script()` could be now "duplicated" since it's call every `get_the_ratings()` rather than once at `wp_enqueue_script()`.
The reason is to allow the user to choose at display time whether this particular voting widget is going to be bound to comment or not (rather than being a generic option affecting every voting system).

If this causes any issue or even doubts, I could try to find a less intrusive way to provide the feature.
But the point is that when one calls `(get_)the_rating(XXX)` he should be able to define some client-side behaviors => thus the need to affect the javascript variables. Alternatives solutions welcomed

**Pull request merged**
